name: Update README

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v3
      
      - uses: gusmg90/README@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
